### ISSUE TITLE
Crash with docker in docker setup

### ISSUE THREAD

**Issue by fedepaol** [intel/sriov-network-device-plugin#141]
Hi, I am experiencing a crash of the plugin with a docker in docker setup. The cluster is running in [kind](https://github.com/kubernetes-sigs/kind) and I moved only the relevant sriov devices into the node namespace.

The thing is, the devices are present inside the container sysfs **but** the link name is not present inside the `/net` subfolder.

I think the dp plugin could filter the devices that do not belong to the current namespace.

This is from the host:
```
[root@xxx kubevirt]# ls /sys/bus/pci/devices/0000:01:00.0/net/
eno1
```
The same path `/sys/bus/pci/devices/0000:01:00.0/net/` exists inside the container (and gets fetched by the dp) but it's empty, causing the crash.

The crash stack / log is the following:
```
I0626 09:50:41.900492      14 manager.go:72] Using Deprecated Devie Plugin Registry Path
I0626 09:50:41.900550      14 main.go:44] resource manager reading configs
I0626 09:50:41.900768      14 manager.go:98] ResourceList: [{ResourceName:sriov IsRdma:false Selectors:{Vendors:[] Devices:[] Drivers:[] PfNames:[]}}]
I0626 09:50:41.900840      14 main.go:60] Discovering host network devices
I0626 09:50:41.900855      14 manager.go:179] discovering host network devices
I0626 09:50:41.992936      14 manager.go:209] discoverDevices(): device found: 0000:01:00.0	02          	Broadcom Inc. and...	NetXtreme BCM5720 2-port Gigabit Ethe...
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/intel/sriov-network-device-plugin/pkg/utils.GetPfName(0xc0008844f5, 0xc, 0xf964e8, 0x0, 0x0, 0x0)
	/usr/src/sriov-network-device-plugin/.gopath/src/github.com/intel/sriov-network-device-plugin/pkg/utils/utils.go:69 +0x310
github.com/intel/sriov-network-device-plugin/pkg/resources.NewPciNetDevice(0xc0008be340, 0xb24540, 0xc00013c8a0, 0x0, 0x0, 0x4, 0x4)
	/usr/src/sriov-network-device-plugin/.gopath/src/github.com/intel/sriov-network-device-plugin/pkg/resources/pciNetDevice.go:46 +0xdb
main.(*resourceManager).discoverHostDevices(0xc0000d5b80, 0x0, 0xa656fa)
	/usr/src/sriov-network-device-plugin/.gopath/src/github.com/intel/sriov-network-device-plugin/cmd/sriovdp/manager.go:227 +0x3e3
main.main()
	/usr/src/sriov-network-device-plugin/.gopath/src/github.com/intel/sriov-network-device-plugin/cmd/sriovdp/main.go:61 +0x20c
```

**Comment by ahalim-intel** [comment]
@fedepaol Thanks for raising this issue. We will need to look into the  error handling first. I will look into that.

**Comment by ahalim-intel** [comment]
Closing this issue as #143 should fix this. Please feel free to re-open if needed.

**Comment by fedepaol** [comment]
I already tried your branch and worked for me (or at least it seems :-) )
Thanks again!
